<header>
        <div style="overflow: auto;">
        <img src="./images/AMS_LogoRED3.png" style="float: left;" width="300" />
        <img src="./images/TUDelft.jpg" style="float: right;" />
    </div>
    <div style="text-align: center;">
        <h1> AMS Data1 </h1>
        <h2>Workshop 6: Loose ends & Numpy</h2>
        <h6>&copy; 2023, TU Delft. Hans Hoogenboom, Creative Commons</h6>     
    </div>
    <br>   
    <br>
</header>

# Python
## Errors

A division by zero results in an error...

In [1]:
a = [2, 3, 5, 0, 9]
b = [5, 6, 0, 7, 9]
for x, y in zip(a, b):
    print(x / y)

0.4
0.5


ZeroDivisionError: division by zero

Can we deal with errors intelligently?

In [ ]:
a = [2, 3, 5, 0, 9]
b = [5, 6, 0, 7, 9]
for x, y in zip(a, b):
    try:
        print(x / y)
    except:
        print("Division by zero?")

0.4
0.5
Division by zero?
0.0
1.0


There are different kind of errors Python can catch. Here is a non exhaustive list:
<br>[Exceptions](https://docs.python.org/3/library/exceptions.html#OSError) and [more exceptional](https://pythonbasics.org/try-except/)

In [ ]:
a = [2, 3, 5, 0, 9]
b = [5, 6, 0, 7, 9]
for x, y in zip(a, b):
    try:
        print(x / y)
    except ValueError:
        print("Division by zero?")

0.4
0.5


ZeroDivisionError: division by zero

Setting the correct type of error helps...

In [ ]:
a = [2, 3, 5, 0, 9]
b = [5, 6, 0, 7, 9]
for x, y in zip(a, b):
    try:
        print(x / y)
    except ZeroDivisionError:
        print("Division by zero?")

0.4
0.5
Division by zero?
0.0
1.0


In [ ]:
class NotFair(Exception):
    pass

employees = ["Alejandro", "Hans", "You", "Monica"]
get_raise = [True, True, False, True]
for y, z in zip(employees, get_raise):
    try:
        if z == True:
            print(y, " gets a raise.")
        if z == False and y == "You":
            raise NotFair
    except NotFair:
        get_raise[2] = True, True

print(get_raise)

Alejandro  gets a raise.
Hans  gets a raise.
Monica  gets a raise.
[True, True, (True, True), True]


## And you thought you were unique?

In Python everything is an object. Everything, even numbers?

In [ ]:
dir(2)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

What are the implications?

In [ ]:
d  = [4, 9, 'abc', [3, 9]]
e = d
e[1] = 12
"???"

'???'

In [ ]:
d[3][1] = {'1' : "first", 2 : 'second'}
print(e)

[4, 12, 'abc', [3, {'1': 'first', 2: 'second'}]]


In [ ]:
f  = [4, 9, 'abc', [3, 9]]
g = f
f[3][1] = {'1' : "first", 2 : 'second'}
print(f)
print(g)

In [ ]:
from copy import deepcopy
g = deepcopy(f)
f[0] = 5
g[1] = 14
print(f)
print(g)

With the deepcopy function you make a unique object. Something to be aware of.

# GIT

![Git, so funny](./images/scared.jpg)

`$ git config --global user.name "John Doe"`
<br>`$ git config --global user.email johndoe@example.com`

There is a [cheat sheet](https://about.gitlab.com/images/press/git-cheat-sheet.pdf)!

[First baby steps](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)

# Numpy

### Introduction
Numpy is a a Python library that provides the user with objects to create vectors and matrices. Numpy calls vectors and arrays multidimensional array objects and yes, in Numpy you can make 5 dimensional matrices whatever they are.  The library comes with a big set of routines for operating on vectors and nD matrices. Below you can find a very short introduction in the use of Numpy.

We can import Numpy the following way:

In [ ]:
import numpy as np

There are several ways you can create a nD array in Numpy, e.g. use a list as input or an Excel/CSV file. Of course you can create an array directly using the following code:

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

# or using a Python list to initialize an array
b = [2, 3, 5]
c = np.array(b)
print(c)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 3 5]


As said, Numpy has a lot of different methods to generate an nD array. Some we will discuss in this notebook but for an overview you can [visit this page](https://numpy.org/doc/stable/user/basics.creation.html).

The [np.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) method creates an array object. The method has several arguments, the most important one being of course the data of which we want to make an array. The second most important one the type of the data, e.g an integer or a float. For scientific calculations we often want to be more precise. Numpy has several "versions" of integers and floats to deal with larger numbers or with numbers that need more decimals like "long integers" and "[doubles](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)". See also the following pages of the Numpy documentation: [Data types](https://numpy.org/doc/stable/user/basics.types.html) and [Scalars, sized aliases](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases). Below we redefine the vector a with 64 bit integers as data type. We can get the type of the data **in** the array by using the *dtype* property.

In [ ]:
a = np.array([1, 2, 3, 4], dtype=np.int64)
print(a.dtype)

int64


Below we create an array, which you probably would call a matrix. The matrix has three rows and three columns. The vector we created above and the matrix below are 4D and 3D in the physical world (e.g. a point in time and a transformation matrix of some geometry). For Numpy, the vector is a 1D array and the matrix a 2D object. Numpy works with axes. A Numpy object with 3 dimensions has 3 axes. Axis 0 points downwards, axis 1 horizontal, axis 2 points in and out of your screen and axis 4...well it is rather difficult to [visualize](https://researchblog.duke.edu/2017/04/26/visualizing-the-fourth-dimension/) that not to mention anything [more then 4D](https://qr.ae/pvV2gl).

In [ ]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

As a convention, you use lower case letters to denote vectors and upper case for matrices. To get the "Numpy" dimension you can use the property *ndim*:

In [ ]:
print(a.ndim)
print(B.ndim)

1
2


But for most physical stuff we are often more interested in the *shape*:

In [ ]:
print(a.shape)
print(B.shape)

(4,)
(3, 3)


To get the number of elements in an array you can use the *size* property:

In [ ]:
print(B.size)

9


### Slicing

You can retrieve data from an vector or matrix using indexing or slicing:

In [ ]:
# get the second row
print("row: \n", B[1])

# get the second element on the second row
print("element: \n", B[1, 1])

# 
print("column: \n", B[:, 1])
print("all rows and first and last column: \n", B[:, [0, 2]])

row: 
 [4 5 6]
element: 
 5
column: 
 [2 5 8]
all rows and first and last column: 
 [[1 3]
 [4 6]
 [7 9]]


Like in Python you can use a range of numbers to create an array. There is an [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) method and there are several \*space methods like linear space, [linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html), logarithmic space, logpsace etc. The linspace method is comparable to creating a domain/range of numbers in Grasshopper. Using the above methods you get a vector of numbers. You can shape them into a matrix using the [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) method. The opposite of a reshape is a flatten method:

In [ ]:
# create some numbers, 0 t0 20. You can use the Python 
# range syntax to set the start, end and steps
my_matr = np.arange(20)
print(my_matr, '\n')

# convert the vector into a matrix
my_matr = my_matr.reshape(4, 5)
print(my_matr, '\n')

# copy some rows and columns from my_matr to create a new matrix
# using slicing
Center = my_matr[1:3, 1:4]
print(Center, '\n')

# convert the matrix to a vector
center = Center.flatten()
print(center, '\n')

# and reshape it again into a matrix
print(center.reshape(3, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 6  7  8]
 [11 12 13]] 

[ 6  7  8 11 12 13] 

[[ 6  7]
 [ 8 11]
 [12 13]]


Multi dimensional arrays were mentioned a fews times. How can you create them and what do they look like? Below an example of a 4 dimensional array:

In [ ]:
weird = np.zeros((3, 2, 3, 4))
print(weird, "\ndims: ", weird.ndim, "\nshape: ", weird.shape, "\nsize: ", weird.size)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]] 
dims:  4 
shape:  (3, 2, 3, 4) 
size:  72


You can easily figure out the dimension of an array by counting the number of **\[** when declaring an array.

Below a few more Numpy methods to create arrays and vectors. When you create an empty array with a certain number of elements, the array is not initialized: it will be filled with random data! Always initialize data before you use it...

In [ ]:
print(np.empty(3))
print(np.ones(3))
print(np.zeros(3))
print(np.random.rand(3))
print(np.arange(3))
print(np.arange(0, 11, 3))

[2.12199579e-314 1.17770766e-311 5.53353523e-321]
[1. 1. 1.]
[0. 0. 0.]
[0.4779191  0.1756314  0.37423765]
[0 1 2]
[0 3 6 9]


In [ ]:
# above we created vectors, below some matrix variants
# float is the default type, use dtype to change this
print(np.zeros((2, 2, 3)), "\n")
print(np.ones((3, 3), dtype=int))

### Merging nD arrays
Sometimes you want to merge arrays, like in plain Python, appending or extending a list. In Numpy there is one general method called concatenate that does this for you. For convenience there are two other methods called vstack and hstack. Let's see what they do.

We create two matrices and want to add them together (element by element addition):

In [ ]:
import numpy as np
A = np.arange(20).reshape(4, 5)
B = np.arange(15).reshape(3, 5)
print(A, '\n')
print(B, '\n')
C = A + B

The error message might be a bit esoteric but it tells you that you want to add arrays of different dimensions together. This is not allowed in Numpy. How can we fix this. Well, we can add a row of zeros to B so A and B have the same shape.

In [ ]:
zero_row = np.array([0, 0, 0, 0, 0])
#D = np.append(zero_row, ini_array, axis = 0)
B = np.vstack([B, zero_row])
print(A.shape)
print(B.shape)

Now we can add them together:

In [ ]:
C = A + B
print(C)

Another way to add rows and columns to a 2D array is using the np.c_ (for column) or the np.r_ (for rows) "functions". They have a weird construct since they don't use parentheses but the square brackets.

In [ ]:
D = np.array([[0, 1, 2], [0, 2, 0]])
new_col = [1, 2]
print(D.shape)
print(D.ndim)
D = np.c_[D, new_col]
new_row = [4, 4 , 4, 4]
# do note the double []
D = np.r_[D, [new_row]]
print(D.shape)
print(D.ndim)
print(D)

### Calculating with arrays

There are several methods which allow you to calculate with arrays, e.g. vector and matrix multiplication. You would be surprised though that for multiplication the outcome is not what you expect if you followed any linear algebra courses.

In [ ]:
a = np.array([2, 3, 4])
B = np.array([[2, 2, 2], [3, 3, 3], [ 4, 4, 0]])
print(B, "\n\n", a * B)

Numpy multiplies by element by default. In normal mathematics a * B should have produced the vector \[12. 18, 16\]! Numpy uses the \@ symbol for multiplying vectors and matrices the expected way. You can also use the *matmul* method.

In [ ]:
print(a @ B)
print(np.matmul(a, B))

You can use the *[sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)* method to sum over the whole matrix or use the *axis* to indicate if you want to sume columns or rows.

In [ ]:
print(B.sum())
print(B.sum(axis = 1))
print(B.sum(axis = 0))

Or find the minimum and maximum value:

In [ ]:
print(B.min(), B.max())

In maths and phyiscs we often [transpose](https://en.wikipedia.org/wiki/Transpose) a matrix, e.g. columns become rows, rows become columns:

In [ ]:
print(B.transpose())

The [dot](https://en.wikipedia.org/wiki/Dot_product) product of two vectors can be calculated using the *vdot* method:

In [ ]:
a = np.array([4, 2, 0])
b = np.array([3, 1, 0])
c = np.array([-0.5, 1, 0])
print(a @ b)
print(np.vdot(a, c))

If you use normalized vectors, that is vectors with the unit length of 1, the dot product will return the cosine between the two vectors. Unlike Grasshopper where we have a *unit vector* component, there is no method in Numpy. To unitize a vector we need to divide the vector by its length. Then we can use the dot product to calcuate the angle:

In [ ]:
# a**2 is the same as a @ a, then we sum and finally we take the square root
# just standard Pythagoras...
a_norm = a / np.sqrt(np.sum(a ** 2))
print(a)

b_norm = b / np.sqrt(np.sum(b ** 2))
c_norm = c / np.sqrt(np.sum(c ** 2))

print(a_norm @ b_norm)
print(np.vdot(a_norm, c_norm))

The [cross product](https://en.wikipedia.org/wiki/Cross_product) of two vectors gives a third vector perpendicular to these vectors. It is not commutative. The length of the perpendicular vector is the area spanned by the other two vectors.

In [ ]:
x = np.array([1, 0, 0])
y = np.array([0, 1, 0])
print(np.cross(x, y))

What does the cross product of y and x return?

The outer product of two vectors produces a matrix. In physics this is called a [tensor](https://en.wikipedia.org/wiki/Tensor). In solid mechanics tensors are used to describe the relation between a force and the surface upon which this force is acting (a layman's explanation...).

In [ ]:
u = np.array([4, 2, 3])
v = np.array([2, 3, 2])
print(np.outer(u, v))

Above we saw that there were many methods to create an array. Below two more methods for creating arrays. One for creating an [identity](https://en.wikipedia.org/wiki/Identity_matrix) matrix. In physics and Finite Element literature the identity matrix is often called the [Kronecker delta](https://en.wikipedia.org/wiki/Kronecker_deltahttps://en.wikipedia.org/wiki/Kronecker_delta).

In [ ]:
np.identity(3)

Or we can create a diagonal matrix with some values:

In [ ]:
d = np.array([1, 2, 3])
dd = np.diag(d)
dd

We can use the *[trace](https://en.wikipedia.org/wiki/Trace_(linear_algebra))* method to calculate the trace, the sum of the diagonal of a matrix:

In [ ]:
print(dd.trace())

If you have a system of equations, like when with a FEM problem, and you are working within the limits of the yield strength of a material you will have a [system of linear equations](https://en.wikipedia.org/wiki/System_of_linear_equations). In this case you can use the *solve* method from Numpy's *linalg* library.

In [ ]:
u = np.array([2, 3])
V = np.array([[1, 4], [3, 2]])
solution = np.linalg.solve(V, u)
print(solution)

You can only solve a system of linear equations if the determinant of the matrix is larger then 0.

In [ ]:
V_det = np.linalg.det(V)
print(V_det)

u = np.array([1, 2, 1])
W = np.array([[1.5, 1, 2], [2, 2, 2], [3, 2, 4]])
print(np.linalg.det(W))
print(W)

# error!
solution = np.linalg.solve(W, u)
print(solution)

If any colum or row in a matrix can be multiplied by a certain number and that results in a vector that is similar to another or or column in that matrix, you have no solution for that matrix (you get the warning above about the matrix being singular). If you multiply the first row of matrix W you get the third row of the matrix. To make a visual repersentation of this, suppose you want to calculate the vector perpendicular to two parallel vectors, how many solutions would you have?

In the Linear Algebra library of Numpy there are also functions and methods to deal with *eigenvalues* and *eigenvectors* of matrices. 
<br>[Eigenvectors in Machine Learning](https://jonathan-hui.medium.com/machine-learning-linear-algebra-eigenvalue-and-eigenvector-f8d0493564c9)
<br>![Eignevectors](./images/eigenvectors.png)

In [ ]:
from numpy import linalg as LA
W = np.random.rand(9).reshape(3,3)
print(W, '\n')
eigenvalues, eigenvectors = LA.eig(W)
print(eigenvalues)
print(eigenvectors)

For more tutorials see:
<br>[W3Schools Numpy](https://www.w3schools.com/python/numpy/default.asp)
<br>[Numpy Illustrated](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
<br>[Numpy Tutorials](https://numpy.org/numpy-tutorials/)

Hans Hoogenboom</br>
Design Informatics</br>
2023 &copy;